#! /usr/bin/env bash

SCRIPTNAME="$0"

# Save the location of the of the script - it is where the Dockerfile
# resides.
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CMANAGER=podman

IMAGENAME=ambit

ambit_usage () {
    cat <<EOF
Usage: $SCRIPTNAME [COMMAND]

Run Claude Code inside a container where it can only access the given project
directories. The review and source control operations are assumed to happen
outside of the container.

Commands:

    run [PROJECT]+  - run the container and give it access to one or more
                      project directories; automatically builds the image
                      containing the agents and dependencies, if it does not
                      exist

    build           - build an image containing the agents and dependencies

    help            - show this message

Examples:

    $SCRIPTNAME run /path/to/project1 /path/to/project2

EOF
}

ambit_build () {
    # Use `--no-cache` to make sure we always get the most recent
    # packages if rebuilding explicitly.
    $CMANAGER build --no-cache -t $IMAGENAME $SCRIPTDIR
}

ambit_run () {
    # Build the image if it does not exist.
    $CMANAGER images -q $IMAGENAME | grep -q . || ambit_build
    # Ensure state/config directories exist.
    mkdir -p .claude .gemini
    # Build volume mounts and container name from all provided paths.
    local volumes=""
    for path in "$@"; do
        host_path="$(realpath "$path")"
        local container_path="$(basename "$host_path")"
        volumes="$volumes -v $host_path:/workspace/$container_path"
    done
    # Make a distinct container ID.
    local container_id="$(echo -n "$@" | sha256sum | cut -c1-8)"
    # Start the container with all project directories mounted into
    # `/workdir`.
    $CMANAGER run -it --rm \
           $volumes \
           -v "$(pwd)/.gemini":/root/.gemini \
           -v "$(pwd)/.claude":/root/.claude \
           --name "ambit-$container_id" \
           $IMAGENAME
}

case "$1" in
    build)
        ambit_build
        ;;
    run)
        shift
        ambit_run "$@"
        ;;
    help)
        ambit_usage
        ;;
    *)
        ambit_usage
        exit 1
        ;;
esac
